################################
# Run Linter against code base #
################################


name: GitHub's Super Linter
on: push

jobs:

  run-linters:
    name: GitHub's Super Linter
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: github/super-linter@v4
     
      - name: Run GitHub Super Linter
        uses: github/super-linter@v4

        env:
          VALIDATE_ALL_CODEBASE: true
          VALIDATE_CLANG_FORMAT: false
          DEFAULT_BRANCH: master
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
